name: Build and publish package

on:
  push:
    branches:
      - master

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          path: workerpool
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@ierp-ai'

      # Install and build
      - run: npm install -g yarn && npm build

      # Test and converage
      - run: npm test && npm coverage

      # Publish 
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.CI_GPR_TOKEN}}
